ALTER TABLE `attributes` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `categories` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `companies` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `company_assignees` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `company_attachment_categories` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `company_attachments` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `company_contacts` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `contacts` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `cost_snapshots` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `customer_follow_ups` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `customer_price_history` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `customers` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `follow_up_records` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `material_boards` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `material_categories` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `material_colors` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `material_suppliers` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `material_types` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `media_library` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `operation_logs` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `order_items` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `order_status_history` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `orders` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `permissions` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `positions` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `price_history` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_batches` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_categories` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_category_links` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_images` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_suppliers` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_tag_links` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `product_variants` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `products` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `quotation_approvals` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `quotation_batches` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `quotation_items` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `quotation_templates` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `quotation_versions` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `quotations` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `supplier_categories` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `suppliers` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `system_settings` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `tags` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user_invitations` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `variant_customer_links` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `variant_images` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `variant_materials` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `variant_pricing` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `variant_pricing_history` MODIFY COLUMN `erpCompanyId` int NOT NULL;--> statement-breakpoint
ALTER TABLE `variant_suppliers` MODIFY COLUMN `erpCompanyId` int NOT NULL;